### ISSUE TITLE
--pi changes reported percent identities

### ISSUE THREAD

**Issue by snayfach** [marbl/MashMap#18]
I ran the program using the commands:
`mashmap -s 1000 -f none -r ref.fna -q qry.fna -o mash_map.tsv -t 1`
and 
`mashmap -s 1000 -f none -r ref.fna -q qry.fna -o mash_map.tsv -t 1 --pi 94`

Using the 1st command, the maximum reported % identity is ~91. Using the second command, there are numerous alignments to the same reference sequence with percent identities ranging from 91 to 95.

Here is an example of one alignment from the second command:

191 | 2173 | 1000 | 1999 | - | 2775506989\|Ga0263387_11 | 8363872 | 1652253 | 1653252 | 95.6678
-- | -- | -- | -- | -- | -- | -- | -- | -- | --

A few questions: why are the alignments different using the --pi flag? Which alignments are correct? Why are alignments with % id < 94 reported when using the --pi 94 flag?

**Comment by cjain7** [comment]
Since Mashmap is an approximate method, the % id is an estimated identity using jaccard similarity of kmers. The estimate also has a statistical error, so we don't filter out mappings that fall below specified cut-off.

The identity estimate is better with higher sketch size, so your first run should serve you better. If the accuracy of % id is critical in your analysis, I recommend running an smith-waterman alignment to validate all the mappings.

**Comment by snayfach** [comment]
Got it thanks. I'd recommend adding that info to your README. Specifically that using the --pi flag may result in less accurate results.
