### ISSUE TITLE
about mashmap.out result

### ISSUE THREAD

**Issue by zhoudreames** [marbl/MashMap#36]
![image](https://user-images.githubusercontent.com/54714639/138654482-7cdfe62f-7ad6-4e3d-9dfa-24f11d6fe967.png)
the results looks like strange，Why can sequences with length 1914830 be fully aligned to sequences with length 2645 ？

**Comment by cjain7** [comment]
Thanks for sharing the sequences.
It looks like the longer sequence (-q 1.fa, query) is a tandem repeat. Mashmap splits the longer sequence into non-overlapping sequences; each of them align to the reference (short sequence 2.fa). At this point, it should have ideally reported individual alignments but it incorrectly merges all alignments because they are located within a threshold range on the reference sequence. The merging algorithm in Mashmap can be improved, I think it should ideally use a co-linear chaining mechanism instead. 

Anyways, I won't recommend using Mashmap for tandem repeats like these; k-mer jaccard similarity is not reliable here.

**Comment by zhoudreames** [comment]
thanks for your reply~
